# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Test

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"
    types:
      - "opened"
      - "synchronize"

jobs:
  test:
    name: Tesdt
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout 
      uses: actions/checkout@v3
    - name: Use Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'
        registry-url: 'https://registry.yarnpkg.com'
        cache: 'yarn'
    - name: Install Dependencies
      run: yarn install --frozen-lockfile --production=false
    - name: Run Test
      run: yarn test:coverage
#    - name: Coverage zgosalvezhttps://github.com/yukha-dw/test-repo/pull/1
#      # https://github.com/marketplace/actions/report-lcov
#      uses: zgosalvez/github-actions-report-lcov@v1
#      if: github.event_name == 'pull_request'
#      with:
#        coverage-files: ./coverage/lcov.info
#        minimum-coverage: 90
#        artifact-name: code-coverage-report
#        github-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Check Coverage
      # https://github.com/marketplace/actions/report-nyc-coverage
      uses: sidx1024/report-nyc-coverage-github-action@v1.2.6
      with:
        # Path to coverage file generated by "nyc report".
        # Default: coverage-summary.json
        coverage_file: "coverage/coverage-summary.json"

        # Path to coverage file generated by "nyc report" for the base branch (for
        # comparison)
        # Default: .base_nyc_output/coverage-summary.json
        # base_coverage_file: ""

        # Template file to be used for GitHub PR comment. Markdown and Svelte are
        # supported.
        # Default: comment-template.md
        comment_template_file: "comment-template.md"

        # "replace" or "new"
        # Default: replace
        comment_mode: "replace"

        # An alternative GitHub token, other than the default provided by GitHub Actions
        # runner. Optional.
        # Default: ${{ github.token }}
        github_token: ${{ secrets.GITHUB_TOKEN }}

        # Absolute path to the source files. The path will be trimmed from the coverage
        # data. Optional. Default is the github workspace directory with a trailing slash.
        # Default: ${{ format('{0}/', github.workspace) }}
        sources_base_path: ${{ format('{0}/', github.workspace) }}

        # Specify the order for coverage types to be included in the output table. (S:
        # statements, B: branches, F: functions, L: lines). Missing types will be
        # excluded.
        # Default: SBFL
        files_coverage_table_output_type_order: "SBFL"