# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Test

on:
  push:
    branches:
      - "**"

jobs:
  test:
    name: Test
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout 
      uses: actions/checkout@v3
    - name: Use Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'
        registry-url: 'https://registry.yarnpkg.com'
        cache: 'yarn'
    - name: Install Dependencies
      run: yarn install --frozen-lockfile --production=false
    - name: Run Test
      run: yarn test:coverage
    - name: Comment Coverage
      uses: sidx1024/report-nyc-coverage-github-action@v1.2.6
      # https://github.com/marketplace/actions/report-nyc-coverage
      with:
        coverage_file: "coverage/coverage-summary.json"
        comment_template_file: "comment-template.md"
        comment_mode: "replace"
        github_token: ${{ secrets.GITHUB_TOKEN }}
        sources_base_path: ${{ format('{0}/', github.workspace) }}
        files_coverage_table_output_type_order: "SBFL"
    - name: Check Coverage
      uses: terencetcf/github-actions-lcov-minimum-coverage-checker@v1.4.1
      # https://github.com/marketplace/actions/lcov-minimum-test-coverage-checker
      with:
        coverage-file: coverage/lcov.info
        minimum-coverage: 95